// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztrcqheowqqbtjepdcgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cmNxaGVvd3FxYnRqZXBkY2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Mjc2ODYsImV4cCI6MjA3NDQwMzY4Nn0.UAuJ8PL4mU1Q77DvX0bHytR6Roa0I5YMajsDnBE8gFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});